### ISSUE TITLE
Incompatible Declaration of toArray Method in PhraseResource

### ISSUE THREAD

**Issue by aqshah20** [MohmmedAshraf/laravel-translations#125]
When attempting to use the package, I encounter an error due to an incompatible declaration of the toArray method in Outhebox\TranslationsUI\Http\Resources\PhraseResource. The error message is as follows:

Declaration of Outhebox\TranslationsUI\Http\Resources\PhraseResource::toArray(Illuminate\Http\Request $request) must be compatible with Illuminate\Http\Resources\Json\JsonResource::toArray($request)

**Comment by MohmmedAshraf** [comment]
Hi @aqshah20 , Which laravel version you use?

**Comment by aqshah20** [comment]
Hello @MohmmedAshraf,

Thank you for your quick response. I was trying to install it on Laravel 9 but encountered an issue. It seems I need to upgrade my Laravel version.

**Comment by MohmmedAshraf** [comment]
Laravel 10/11 needed

**Comment by aqshah20** [comment]
Yes, I have upgraded now working fine to me

**Comment by aqshah20** [comment]
At login and after adding phrases, and publishing on every POST request, I am encountering a 419 CSRF token error. I have currently disabled CSRF in my Kernel file, but I am still experiencing this issue.
