### ISSUE TITLE
Packages make the project very heavy

### ISSUE THREAD

**Issue by achmadhadikurnia** [MohmmedAshraf/laravel-translations#23]
Hi, after I installed and implemented the package configuration. my project gets heavy on page load even it takes 4 seconds just to show login page.
My project is running on Laravel 9 PHP 8.0.25

![image](https://user-images.githubusercontent.com/4408971/215637150-48bfcfd4-b568-4f09-9b9a-d973aa39a2e1.png)

**Comment by MohmmedAshraf** [comment]
Hi, have you tried to cache the icons by running the following command? 

```bash
php artisan icons:cache
```

Let me know if this fixes your issue

**Comment by kmaking** [comment]
@MohmmedAshraf I have tried and it is working

**Comment by MohmmedAshraf** [comment]
@kmaking Thank you

**Comment by achmadhadikurnia** [comment]
Sorry I just removed the package for a while. 
When I need I will install again.
