### ISSUE TITLE
Customizing the package.

### ISSUE THREAD

**Issue by Minhazul-Islam18** [MohmmedAshraf/laravel-translations#34]
### Discussed in https://github.com/MohmmedAshraf/laravel-translations/discussions/33

<div type='discussions-op-text'>

<sup>Originally posted by **Minhazul-Islam18** May 28, 2023</sup>
Hello Ashraf. I'm using your package and it's very enjoyable. Now, I want to customize routes & other files. How can I do that?

.
Thanks in Advance</div>

**Comment by Minhazul-Islam18** [comment]
@PovilasKorop Help me, please.

**Comment by PovilasKorop** [comment]
@Minhazul-Islam18 sorry I don't have any free time this Summer for such unplanned activities

**Comment by MohmmedAshraf** [comment]
@Minhazul-Islam18 You can change the routes/domain from the package config file
