### ISSUE TITLE
The "/xxxx/resources/lang/en" directory does not exist.

### ISSUE THREAD

**Issue by rabol** [MohmmedAshraf/laravel-translations#36]
Hi

Just installed this package and is running the 
```
php artisan translations:import
```

and get the error

It's actually correct that the directory does not exists, and that is on purpose as I use /lang for my translations

**Comment by MohmmedAshraf** [comment]
Hi @rabol Thank you for reporting this issue, I will ship the fix in the next release maybe today 😄
