### ISSUE TITLE
Unable to locate a class or view for component [flag-language-en].

### ISSUE THREAD

**Issue by TK2011-TH** [MohmmedAshraf/laravel-translations#4]
Hi, after I installed and imported the data I went to /translations page but it shown "Unable to locate a class or view for component [flag-language-en]." 

My project is run on Laravel 9 on Sail container

**Comment by R00118189** [comment]
Unable to locate class or view [components.input] for component [input]. when accessing `/translations`
This happens after `php artisan translations:import`, beforehand, it loads but indicates we should run the import command.

**Comment by elguitarraverde** [comment]
@TK2011-TH @R00118189 I can't reproduce this error. can you provide screenshot of the error and composer.json file?
