### ISSUE TITLE
Publish not work with me & save translate not work on 0.1.1 - 2023-11-11

### ISSUE THREAD

**Issue by NulledOz** [MohmmedAshraf/laravel-translations#46]
I Downgrade to 0.0.7 - 2023-06-28 and all work fine.

*********
استخدمت النسخة السابقة (0.0.7) تعمل بشكل سليم ولكن النسخة رقم (0.1.1) لا يتم فيها حفظ الترجمة ولا يتم انشاء الملف في مجلد اللغة

**Comment by MohmmedAshraf** [comment]
Hi @NulledOz ,

Please update the the latest version.

@VladimirFrunza Thank you.
