### ISSUE TITLE
Bug: Required parameters are missing

### ISSUE THREAD

**Issue by raonikhil** [MohmmedAshraf/laravel-translations#48]
**Version: "outhebox/laravel-translations": "^0.1.2"**

- I've installed the package out of the box and ran /translations to get this error. 
- I saw this issue as closed where you commented to upgrade it to the latest version which I am already on and still I see this issue. 

Can you please help me with this?

<img width="1525" alt="MyVdwLease 2024-01-10 21-33-50" src="https://github.com/MohmmedAshraf/laravel-translations/assets/2131177/cc38cae6-1b87-4c76-9899-baabc261a91d">

**Comment by Perzonallica** [comment]
Same issue here. I have the `0.1.2` version.

**Comment by Perzonallica** [comment]
Try this:

1. Open file on line `vendor/outhebox/laravel-translations/src/Livewire/PhraseForm.php:70`
2. Change the line to this: `if (! str_contains($this->phrase->source->value, ":$parameter")) {`

Originally it was: `$this->phrase->value`, however it returns `null`

**Comment by raonikhil** [comment]
thank you, this worked, waiting for this to be updated in the package itself so I can use it on production as well

**Comment by MohmmedAshraf** [comment]
Hi @raonikhil,

Just wanted to let you know that a significant update is on the way, and it will address all the issues, also with many new features as well.

Thanks a lot for your patience!

**Comment by MohmmedAshraf** [comment]
Kindly upgrade to the newest version and carefully review the installation instructions, as this release involves completely different versions.
