### ISSUE TITLE
Migration issue

### ISSUE THREAD

**Issue by aeq-dev** [MohmmedAshraf/laravel-translations#52]
Hello,
I'm getting this error on migrating ...
![Screenshot from 2024-01-19 22-41-57](https://github.com/MohmmedAshraf/laravel-translations/assets/81385994/a4bf12ae-18c5-403c-9076-b51a9810b29d)

**Comment by MohmmedAshraf** [comment]
Hi @aeq-dev,

which version you trying to install, also please if you have an old version of the package try to remove all related database tables from the database before installing v1.0.1

**Comment by aeq-dev** [comment]
First time I installed it on Laravel 10

**Comment by codinglabe** [comment]
In HasAttributes.php line 1183:
                                                                                                          
  Outhebox\TranslationsUI\Enums\RoleEnum::from(): Argument #1 ($value) must be of type int, string given
  
  please solve this
