### ISSUE TITLE
Bugs in installation

### ISSUE THREAD

**Issue by MomoDerDodo** [MohmmedAshraf/laravel-translations#53]
While following the install instructions i ran into a few bugs.

When i try to run the migrations i get the following error: 
![grafik](https://github.com/MohmmedAshraf/laravel-translations/assets/38343956/0210c9ae-9c21-463c-b90f-47c38f35bfad)

I changed the type of the status column to `string` and was able to proceed.

Then after i follow the steps i get to the contributor creation. After entering the prompted data i get the the following error:
![grafik](https://github.com/MohmmedAshraf/laravel-translations/assets/38343956/2f96dbc7-adde-4839-94ce-8f9485603415)

**Comment by MohmmedAshraf** [comment]
Hi @Morice99,

I've tried installing the package on fresh Laravel multiple times, and I didn't encounter a similar issue. Could you please provide more information about your PHP version, Laravel version, and the database driver you're using?

**Comment by Morice99** [comment]
Hi, thanks for the reply. 

My versions are:
- PHP: 8.1
- Laravel: 10.41.0

My Database driver is the default configured mysql that looks like this:

 ```
 'mysql' => [
          'driver' => 'mysql',
          'url' => env('DATABASE_URL'),
          'host' => env('DB_HOST', '127.0.0.1'),
          'port' => env('DB_PORT', '3306'),
          'database' => env('DB_DATABASE', 'forge'),
          'username' => env('DB_USERNAME', 'forge'),
          'password' => env('DB_PASSWORD', ''),
          'unix_socket' => env('DB_SOCKET', ''),
          'charset' => 'utf8mb4',
          'collation' => 'utf8mb4_unicode_ci',
          'prefix' => '',
          'prefix_indexes' => true,
          'strict' => true,
          'engine' => null,
          'options' => extension_loaded('pdo_mysql') ? array_filter([
              PDO::MYSQL_ATTR_SSL_CA => env('MYSQL_ATTR_SSL_CA'),
          ]) : [],
      ]
```

**Comment by MomoDerDodo** [comment]
Also i tried it with default and fresh laravel installation and it also fails

**Comment by NoahNxT** [comment]
Same issue here, seems to be an issue with the **TEXT** type of the _status_ column. After some digging I found that adding a default value to a **TEXT** column type isn't possible out of the box, herefore you have to configure your mysql installation a specific way, and also run a version 8.0+

replacing it by the column type **STRING** like this:
`            $table->string('status')->default(StatusEnum::active->value);
`

solves it. 

Looking at the code this field is also only for the statuses which you pre-integrated. So adding a **TEXT** type column would be unneccesary, which make a **STRING** type enough.

**Comment by MohmmedAshraf** [comment]
Hi @MomoDerDodo,

This should be fixed by @NoahNxT, please try the new release.

**Comment by MomoDerDodo** [comment]
The fist bug is fixed, thank you :)

But the second one with the Contributer Creation is still present for me. 

` Outhebox\TranslationsUI\Enums\RoleEnum::from(): Argument #1 ($value) must be of type int, string given  `
