### ISSUE TITLE
Unable to remove the package :( 

### ISSUE THREAD

**Issue by raonikhil** [MohmmedAshraf/laravel-translations#56]
Please help!!

<img width="941" alt="myvdwlease_server - Container - Docker Desktop 2024-01-22 14-06-55" src="https://github.com/MohmmedAshraf/laravel-translations/assets/2131177/e14cd4a7-b455-4d93-a7c4-8c659beb967a">

**Comment by MohmmedAshraf** [comment]
Hi @raonikhil,

Remove the package translation service provider from `config/app.php`

**Comment by raonikhil** [comment]
It worked, thanks!
