### ISSUE TITLE
Export error when key ends with period symbol

### ISSUE THREAD

**Issue by vitorcrovador** [MohmmedAshraf/laravel-translations#57]
Hello. I noticed that when I run the artisan translations:export command and the key contains a period (.) at the end it breaks the generated json.

Before:
![image](https://github.com/MohmmedAshraf/laravel-translations/assets/22171591/9148d55e-9791-422c-8393-e0924fe0655e)

After Export:
![image](https://github.com/MohmmedAshraf/laravel-translations/assets/22171591/bb61a4ba-7a64-4818-9adc-6117beab1dc4)

**Comment by MohmmedAshraf** [comment]
Hi @vitorcrovador,

The issue should be fixed in latest release give it a try and let me know, thanks for your feedback!
