### ISSUE TITLE
Various issues

### ISSUE THREAD

**Issue by mortenscheel** [MohmmedAshraf/laravel-translations#61]
Fresh install in Laravel 10 project.

- create_translations_table wasn't published. had to copy it manually
- pages/translations/index uses the wrong data type for `props.translations`. The translations are not paginated, so the type is simply `Record<string, Translation>`.

Not sure if it's just a problem in my environment, but running `npm run dev` in the package folder only works for a couple of minutes, then the process crashes with an out of memory error:
```
FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory```
```

On a side note, it would be great if you could opt out of the custom Contributor auth system and just use the app's own User. It probably makes the package development easier, but it's annoying to have to create separate users in order to manage translations.

**Comment by MohmmedAshraf** [comment]
This should be fixed in the latest release.
