### ISSUE TITLE
500 when Model::shouldBeStrict() is used in the application

### ISSUE THREAD

**Issue by ahtinurme** [MohmmedAshraf/laravel-translations#65]
![Screenshot 2024-02-02 at 15 46 26](https://github.com/MohmmedAshraf/laravel-translations/assets/282119/34ab1d72-45df-4a11-be53-d81a8b156298)
![Screenshot 2024-02-02 at 15 46 31](https://github.com/MohmmedAshraf/laravel-translations/assets/282119/eebcc7d9-db17-4cf8-994f-1a365ea070b7)
Seems to be related more specifically to Model::preventAccessingMissingAttributes()
Using the latest version (1.0.5)

**Comment by MohmmedAshraf** [comment]
Hello @ahtinurme,

Certainly, as the progress isn't stored in the database; it's dynamically calculated.

**Comment by ahtinurme** [comment]
I think this one can be closed as it falls back to Laravel framework itself, and I understand they are not planning to fix it.
