### ISSUE TITLE
Incorrect work with subfolders

### ISSUE THREAD

**Issue by Aqamarine228** [MohmmedAshraf/laravel-translations#7]
<ul>
    <li>Laravel Version: 9.19</li>
    <li>Package version:  0.0.3</li>
    <li>PHP version: not relevant</li>
    <li>Database Driver: MySQL</li>
    <li>Operating System & Version: MacOs Monterey 12.5.1</li>
    <li>Browser Type & Version: Safari 15.6.1</li>
</ul>

### Description:

All language files are imported in database correctly, files from lang subfolders also, for example: lang/en/email/layout.php.
After any pushed changes all files not from subfolders are changed correctly. All files from subfolders, even if their changes have been pushed, remain untouched, but their changed copy is created inside lang/{language} folder.

### Detailed steps to reproduce the issue on a fresh laravel project with installed package:

Create subfolder inside your lang/{language} folder and add there any non empty translation file. Import translations and publish any changes.

**Comment by MohmmedAshraf** [comment]
Hi @Aqamarine228, at the moment subfolders within the language folder are not supported. Additionally, having subfolders within each language folder may not be considered the best approach. However, I am considering adding support for this in the future, specifically with the vendor folder support release, Thanks for your feedback
