### ISSUE TITLE
The value format for the key field is invalid. Error 

### ISSUE THREAD

**Issue by inkomomutane** [MohmmedAshraf/laravel-translations#70]
Hi, @MohmmedAshraf
I face this error when i want to add a key with blank space to translations using the dashboard. 
but importing my Json files are all ok. 

![Screenshot from 2024-02-07 11-17-07](https://github.com/MohmmedAshraf/laravel-translations/assets/57417802/32a8cce0-f6f9-41b4-877f-f0940b018525)

i tried to find out why and i found that regex validation i think that added a blank space cold solve. 

https://github.com/MohmmedAshraf/laravel-translations/blob/9b40b5782b4ad43399de66d5ef13244fe24ecb00/src/Http/Controllers/SourcePhraseController.php#L57

Thanks.

**Comment by MohmmedAshraf** [comment]
Hi @inkomomutane ,

I will fix this next release
