### ISSUE TITLE
not working with `JsonResource::withoutWrapping();`

### ISSUE THREAD

**Issue by SalemCode8** [MohmmedAshraf/laravel-translations#78]
If the laravel application is using `JsonResource::withoutWrapping();` the whole translation ui won't work.

after a little of checking looks like in the translations main page the code is accessing the translations as follows `translations.data` which is in case of `JsonResource::withoutWrapping();` It will be just `translations`.

tried to do this change as PR but as the package only have the compiled JS code it'll be so hard to do so

**Comment by SalemCode8** [comment]
after another look it looks like this affecting every page in the ui not only the main page

**Comment by MohmmedAshraf** [comment]
This should be fixed in the latest release.
