### ISSUE TITLE
Add contributor issues

### ISSUE THREAD

**Issue by ngotuananh101** [MohmmedAshraf/laravel-translations#79]
Hello,
I getting this message when i try to add new contributor

![image](https://github.com/MohmmedAshraf/laravel-translations/assets/64295974/468efd31-8098-4e63-9e63-48cc721bebc1)

**Comment by zeyad-k** [comment]
did you solve it ?

**Comment by amshehzad** [comment]
@MohmmedAshraf I've opend a PR to fix this here #86

**Comment by MohmmedAshraf** [comment]
Thanks @amshehzad
