### ISSUE TITLE
Emoji errors

### ISSUE THREAD

**Issue by kimagroup** [MohmmedAshraf/laravel-translations#95]
Hey, it seems that flags from https://twemoji.maxcdn.com/ aren't loading anymore. Can you please check? Thanks!

**Comment by linuslabo** [comment]
That's probably because twemoji.maxcdn.com does not have a valid certificate.

**Comment by kimagroup** [comment]
Of course, but would be great to add alternative.

**Comment by MohmmedAshraf** [comment]
This should be fixed in the latest release.
