### ISSUE TITLE
Issues when using JsonResource::withoutWrapping()

### ISSUE THREAD

**Issue by JorgenSolli** [MohmmedAshraf/laravel-translations#97]
Hey! Great stuff in v1! Was excited to test it out, but didn't get too far. I realized quickly that fetching the translations will fail if you have set this in your AppServiceProvider. 

```
JsonResource::withoutWrapping();
```
Error:
```
Cannot read properties of undefined (reading 'length')
```

When attempting to read:
```
!a.translations.data.length
```

I don't think this will be an issue for most people, but the functionality is documented here https://laravel.com/docs/11.x/eloquent-resources#data-wrapping so I'm probably not the last. 

Not sure what the best fix is, but now you're aware of this at least :)

**Comment by JorgenSolli** [comment]
How did I not see this issue already... My bad
Related: #78

**Comment by MohmmedAshraf** [comment]
Hi @JorgenSolli thank you for your feedback i will try to fix this asap

**Comment by MohmmedAshraf** [comment]
This should be fixed in the latest release.
