### ISSUE TITLE
Migration miss : create_languages_table file

### ISSUE THREAD

**Issue by tmvlksoftware** [MohmmedAshraf/laravel-translations#98]
- Miss create_languages_table file on migration
- php artisan translations:import : get error "SQLSTATE[42P01]: Undefined table: 7 ERROR:  relation "ltu_languages" does not exist  "
<img width="771" alt="Screenshot 2024-04-17 at 02 48 58" src="https://github.com/MohmmedAshraf/laravel-translations/assets/160385852/7b03d0bc-9c53-416c-b436-2d26caee7ccd">

**Comment by adereksisusanto** [comment]
> * Miss create_languages_table file on migration
> * php artisan translations:import : get error "SQLSTATE[42P01]: Undefined table: 7 ERROR:  relation "ltu_languages" does not exist  "
> 
> <img alt="Screenshot 2024-04-17 at 02 48 58" width="771" src="https://private-user-images.githubusercontent.com/160385852/322979446-7b03d0bc-9c53-416c-b436-2d26caee7ccd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM2MDExNTgsIm5iZiI6MTcxMzYwMDg1OCwicGF0aCI6Ii8xNjAzODU4NTIvMzIyOTc5NDQ2LTdiMDNkMGJjLTljNTMtNDE2Yy1iNDM2LTJkMjZjYWVlN2NjZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyMFQwODE0MThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05YjM2NmIxYjIwYTVhOTVlZmJkMmU1YmZiN2Q5ZmFjNzUzMjFlZjA2OWIwNGQxYjFlZGFiODIzMGZjMzE0MWQ4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.-BbeqrPfnjsJWY1XLu00zwcMpsqMuXIg9iJdH4iwMB0">

![Screenshot (43)](https://github.com/MohmmedAshraf/laravel-translations/assets/34746706/9ffb0212-8f56-4b6c-8fab-1decc1601854)
 check > https://laravel.com/docs/11.x/database#introduction

**Comment by MohmmedAshraf** [comment]
Hi @tmvlksoftware this should be fixed in latest release
